<?php
/**
 * @file
 * Code for the Basic Text Block feature.
 */

include_once 'bean_text_block.features.inc';


/**
 * Implements hook_form_alter().
 */
function bean_text_block_form_bean_form_alter(&$form, &$form_state, $form_id) {

  // Hide the view mode selector if there is only one to choose from.
  // This really should be built into the Bean module itself. ;)
  if(count($form['view_mode']['#options']) == 1) {
    $form['view_mode']['#type'] = 'hidden';
  }

  if ($form['#bundle'] == 'text_block') {
    // The basic text block doesn't need a title.
    $form['title']['#type'] = 'hidden';
    // The basic text block uses only the "default" view mode.
    $form['view_mode']['#type'] = 'hidden';

    // Change the label here only. This is so other places outside the scope
    // of this edit form retain the more logical default label "Text Block".
    $form['field_text_block']['und'][0]['#title'] = t('Content');

    // Space is cheap; default to new revision and simplify the log message.
    if (isset($form['revision'])) {
      $form['revision']['is_new_revision']['#default_value'] = true;
      $form['revision']['is_new_revision']['#type'] = 'hidden';
      $form['revision']['default_revision']['#default_value'] = true;
      $form['revision']['default_revision']['#type'] = 'hidden';
      $form['revision']['log']['#type'] = 'textfield';
      unset($form['revision']['log']['#dependency']);
      $form['revision']['log']['#title'] = t('What changed?');
      $form['field_text_block']['#weight'] = $form['revision']['#weight'] - 1;
    }
  }

}
